// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJHf7a_mnHVZ4J-DbKcwF525YWWEpa_8',
    appId: '1:401183573677:web:05e9187c136c527d956824',
    messagingSenderId: '401183573677',
    projectId: 'fir-cloudmsg-codelab',
    authDomain: 'fir-cloudmsg-codelab.firebaseapp.com',
    storageBucket: 'fir-cloudmsg-codelab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpTZYj_EzGSc6E1Vdz3291SD2cX7g750',
    appId: '1:401183573677:android:9b204008442b4bb5956824',
    messagingSenderId: '401183573677',
    projectId: 'fir-cloudmsg-codelab',
    storageBucket: 'fir-cloudmsg-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFX3QtXmMU0__lXFL8DGmpYKTwjVlaqqc',
    appId: '1:401183573677:ios:deb52bcd78fbf803956824',
    messagingSenderId: '401183573677',
    projectId: 'fir-cloudmsg-codelab',
    storageBucket: 'fir-cloudmsg-codelab.appspot.com',
    iosClientId: '401183573677-stsd7vrk32cqg1l8570a3ml9uit380pu.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFX3QtXmMU0__lXFL8DGmpYKTwjVlaqqc',
    appId: '1:401183573677:ios:deb52bcd78fbf803956824',
    messagingSenderId: '401183573677',
    projectId: 'fir-cloudmsg-codelab',
    storageBucket: 'fir-cloudmsg-codelab.appspot.com',
    iosClientId: '401183573677-stsd7vrk32cqg1l8570a3ml9uit380pu.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );
}
